import { RoleDef, RoleId } from "../types/domain";

export const ROLES: Record<RoleId, RoleDef> = {
  worker: {
    id: "worker",
    name: "Worker",
    short: "Proof staff",
    hierarchy: "Worker -> AA/LC -> Branch Manager -> RM",
    pages: [
      { id: "home", label: "Home", emoji: "🏠" },
      { id: "tasks", label: "Tasks", emoji: "✅" },
      { id: "complaints", label: "Complaint", emoji: "🧰" },
      { id: "attendance", label: "Attendance", emoji: "📍" },
      { id: "notifications", label: "Alerts", emoji: "🔔" },
      { id: "profile", label: "Profile", emoji: "👤" },
    ],
  },
  employee: {
    id: "employee",
    name: "Employee",
    short: "Regular staff",
    hierarchy: "Employee -> AA/LC -> Branch Manager -> RM",
    pages: [
      { id: "home", label: "Home", emoji: "🏠" },
      { id: "tasks", label: "Tasks", emoji: "✅" },
      { id: "complaints", label: "Issues", emoji: "⚠️" },
      { id: "attendance", label: "Attendance", emoji: "📍" },
      { id: "notifications", label: "Alerts", emoji: "🔔" },
      { id: "profile", label: "Profile", emoji: "👤" },
    ],
  },
  am: {
    id: "am",
    name: "Admin Assistant",
    short: "Branch Ops Lead",
    hierarchy: "AA/LC -> Branch Manager -> RM",
    pages: [
      { id: "home", label: "Home", emoji: "🏠" },
      { id: "tasks", label: "Tasks", emoji: "🗂️" },
      { id: "complaints", label: "Complaints", emoji: "⚠️" },
      { id: "branch", label: "Branch", emoji: "🏢" },
      { id: "attendance", label: "Attendance", emoji: "👥" },
      { id: "notifications", label: "Alerts", emoji: "🔔" },
      { id: "profile", label: "Profile", emoji: "👤" },
    ],
  },
  branchManager: {
    id: "branchManager",
    name: "Branch Manager",
    short: "Branch oversight",
    hierarchy: "Branch Manager -> RM",
    pages: [
      { id: "home", label: "Overview", emoji: "🏠" },
      { id: "branches", label: "Branches", emoji: "🏢" },
      { id: "monitoring", label: "Task Monitor", emoji: "📈" },
      { id: "issues", label: "Issues", emoji: "🧯" },
      { id: "approvals", label: "Approvals", emoji: "🧾" },
      { id: "visits", label: "Visits", emoji: "🛣️" },
      { id: "notifications", label: "Alerts", emoji: "🔔" },
      { id: "profile", label: "Profile", emoji: "👤" },
    ],
  },
  rm: {
    id: "rm",
    name: "Super Admin / RM",
    short: "Regional control",
    hierarchy: "RM / Super Admin",
    pages: [
      { id: "dashboard", label: "Dashboard", emoji: "📊" },
      { id: "intelligence", label: "Branch Intel", emoji: "🛰️" },
      { id: "alerts", label: "Alert Center", emoji: "🚨" },
      { id: "finance", label: "Issues & Costs", emoji: "💰" },
      { id: "analytics", label: "Analytics", emoji: "📉" },
      { id: "approvals", label: "Approvals", emoji: "🧾" },
      { id: "users", label: "Users", emoji: "🧑‍🤝‍🧑" },
      { id: "settings", label: "Settings", emoji: "⚙️" },
      { id: "notifications", label: "Alerts", emoji: "🔔" },
      { id: "profile", label: "Profile", emoji: "👤" },
    ],
  },
};
